/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package master;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.Connection;

/**
 *
 * @author MYPC
 */
public class NewProduct extends javax.swing.JFrame {

    /**
     * Creates new form NewProduct
     */
    Connection con1=null;
   
    public NewProduct() {
        initComponents();
        setSize(600,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTextField1 = new javax.swing.JTextField();
        pro_pri = new javax.swing.JTextField();
        pur_pri = new javax.swing.JTextField();
        sale_pri = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pro_pri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pro_priActionPerformed(evt);
            }
        });
        getContentPane().add(pro_pri);
        pro_pri.setBounds(230, 120, 270, 30);

        pur_pri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pur_priActionPerformed(evt);
            }
        });
        getContentPane().add(pur_pri);
        pur_pri.setBounds(230, 170, 270, 30);

        sale_pri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sale_priActionPerformed(evt);
            }
        });
        getContentPane().add(sale_pri);
        sale_pri.setBounds(230, 220, 270, 30);

        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(400, 320, 100, 22);

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(230, 320, 100, 22);

        jLabel1.setText("Product Price :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 130, 130, 16);

        jLabel2.setText("Purches price :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 180, 120, 16);

        jLabel3.setText("Sales Price :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 220, 100, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 60, 100, 0);

        jLabel5.setText("Product name :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 80, 110, 16);

        pnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnmActionPerformed(evt);
            }
        });
        getContentPane().add(pnm);
        pnm.setBounds(230, 70, 270, 30);

        jLabel6.setText("Stock :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 280, 70, 16);

        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        getContentPane().add(stock);
        stock.setBounds(230, 270, 270, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("       NEW PRODUCT ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 20, 250, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        this.setVisible(false);
        MasterF.main(new String[2]);
    }//GEN-LAST:event_homeActionPerformed

    private void sale_priActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sale_priActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sale_priActionPerformed

    private void pur_priActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pur_priActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pur_priActionPerformed

    private void pnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnmActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       try{
         con1=InitConnection.initConn();
         PreparedStatement ps=con1.prepareStatement("insert into product (p_name,p_price,pur_price,sale_price,stock) values(?,?,?,?,?)");
        
         ps.setString(1, pnm.getText());
         ps.setInt(2,Integer.parseInt(pro_pri.getText()));
         ps.setInt(3,Integer.parseInt(pur_pri.getText()));
         ps.setInt(4,Integer.parseInt(sale_pri.getText()));
         ps.setInt(5,Integer.parseInt(stock.getText()));
         ps.executeUpdate();
         JOptionPane.showMessageDialog(null," Data inserted Successfully");
         setVisible(false);
         new NewProduct().setVisible(true);
         con1.close();

       }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,"product id is already exist");
            setVisible(false);
            new NewProduct().setVisible(true);
        }
        
    }//GEN-LAST:event_saveActionPerformed

    private void pro_priActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pro_priActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pro_priActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pnm;
    private javax.swing.JTextField pro_pri;
    private javax.swing.JTextField pur_pri;
    private javax.swing.JTextField sale_pri;
    private javax.swing.JButton save;
    private javax.swing.JTextField stock;
    // End of variables declaration//GEN-END:variables
}
